[package]
name = "anthaathi-graphql-file-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anthaathi-graphql-common = { path = "../anthaathi-graphql-common" }
