env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  APP_PORT: ""
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: ""

on:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

name: Build Container Images

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    strategy:
      matrix:
        app: ["anthaathi-crm"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          cache: 'yarn'

      - name: Install yarn packages
        run: yarn install

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build App And Push Development
        if: "github.event.release.prerelease"
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: :apps:${{ matrix.app }}:build -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.username=${{ github.repository_owner }} -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.tag=${{ github.sha }} -Dquarkus.container-image.additional-tags=development -Dnative -Dquarkus.container-image.group=anthaathi

      - name: Build App And Push Latest
        if: "!github.event.release.prerelease"
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: :apps:${{ matrix.app }}:build -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.username=${{ github.repository_owner }} -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.tag=${{ github.sha }} -Dquarkus.container-image.additional-tags=latest -Dnative -Dquarkus.container-image.group=anthaathi

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      # https://github.com/redhat-actions/oc-login#readme
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        if: "github.event.release.prerelease"
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE_DEVELOPMENT }}
